# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='date',
            field=models.DateField(default=datetime.date(2016, 10, 25)),
        ),
    ]
